name: Main

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  buildStep1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'
      - uses: actions/cache@v3
        id: node_modules_cache_id
        env:
          cache-name: node-modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install --frozen-lockfile
      - run: echo "VER_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo "GITHUB_REF) $GITHUB_REF"
      - run: echo "github.ref) ${{ github.ref }}"
      - run: echo "githu.event.release.tag_name) ${{ github.event.release.tag_name }}"
