name: Main

on:
  push:
  pull_request:
  release:
    types: [created]

jobs:
  buildStep1:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      NODE_OPTIONS: --max_old_space_size=4000
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: echo "VER_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo "GITHUB_REF) $GITHUB_REF"
      - run: echo "github.ref) ${{ github.ref }}"
      - run: echo "githu.event.release.tag_name) ${{ github.event.release.tag_name }}"
